

<?php
$imagewidth = 200;
$imageheight = 200;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$imageHelper = $objectManager->get('Magento\Catalog\Helper\Image');
$productRepository = $objectManager->get('Magento\Catalog\Model\ProductRepository');

$randomProductIds = [1, 2, 3, 4, 2058]; 

foreach ($randomProductIds as $productId) {
    $block = $block->getLayout()->createBlock('Practice\ecomm\Block\ProductList');
    $product = $block->abc($productId);
    // $product = $productRepository->getById($productId);

    if ($product && $product->getImage()) {
        $image_url = $imageHelper->init($product, 'product_thumbnail_image')
            ->setImageFile($product->getImage())
            ->resize($imagewidth, $imageheight)
            ->getUrl();
        ?>
        <div class="best-price-product-info">
            <img src="<?= $image_url ?>" alt="<?= $product->getName() ?>">
            <h4><?= $product->getName() ?></h4>
            <p>SKU: <?= $product->getSku() ?></p>
            <p>Giá: <?= $product->getPrice() ?></p>
        </div>
        <?php
    } else {
        ?>
            <p>Sản phẩm không tồn tại hoặc không có hình ảnh.</p>
        <?php
    }
}
?>

