<div class="image">
    <div class="image-wrapper">
        <img src="<?php echo $block->getViewFileUrl('images/B2B-PC-VN.png'); ?>" alt="Image 1" />
        <img src="<?php echo $block->getViewFileUrl('images/B2B-PC-VN.png'); ?>" alt="Image 2" />
    </div>
    <div class="image-block">
        <img src="<?php echo $block->getViewFileUrl('images/B2B-PC-VN.png'); ?>" alt="Image 3" />
    </div>
</div>