<div class="selling-feature">
    <div class="container">
        <div class="block">
            <div class="media list-features">
                <h5>Giao Hàng Miễn Phí</h5>
                <span>Cho đơn hàng 2.000.000đ</span>
            </div>
        </div>
        <div class="block">
            <div class="media list-features">
                <h5>Hàng Chính Hãng</h5>
                <span>Xuất xứ rõ ràng</span>
            </div>
        </div>
        <div class="block">
            <div class="media list-features">
                <h5>Thanh toán an toàn</h5>
                <span>Tiền mặt và thẻ</span><br>
                <span>Hỗ trợ và góp qua thẻ</span>
            </div>
        </div>
        <div class="block">
            <div class="media list-features">
                <h5>Tổng đài CSKH</h5>
                <span>9:00 - 18:00</span>
                <span>Thứ 2 - Thứ 6</span>
            </div>
        </div>
    </div>
</div>