<div class="banner-a">
    <div class="slider">
        <img src="<?php echo $block->getViewFileUrl('images/B2B-PC-VN.png'); ?>" alt="Image 1" />
        <img src="<?php echo $block->getViewFileUrl('images/W4_mb_vn.jpg'); ?>" alt="Image 2" />
        <img src="<?php echo $block->getViewFileUrl('images/W3_pc_vn.jpg'); ?>" alt="Image 3" />
    </div>
    <div class="abc">
        <img src="<?php echo $block->getViewFileUrl('images/B2B-PC-VN.png'); ?>" alt="Image 1" />
        <img src="<?php echo $block->getViewFileUrl('images/W4_mb_vn.jpg'); ?>" alt="Image 2" />
    </div>
</div>