<div class="menu-grid">
    <div class="menu-item">
    <img src="<?php echo $block->getViewFileUrl('images/banner.png'); ?>" alt="Banner Image">
    </div>
    <div class="menu-item">
    <img src="<?php echo $block->getViewFileUrl('images/banner.png'); ?>" alt="Banner Image">
    </div>
    <div class="menu-item">
    <img src="<?php echo $block->getViewFileUrl('images/banner.png'); ?>" alt="Banner Image">
    </div>
    <div class="menu-item">
    <img src="<?php echo $block->getViewFileUrl('images/banner.png'); ?>" alt="Banner Image">
    </div>
    <div class="menu-item">
    <img src="<?php echo $block->getViewFileUrl('images/banner.png'); ?>" alt="Banner Image">
    </div>
    <div class="menu-item">
    <img src="<?php echo $block->getViewFileUrl('images/banner.png'); ?>" alt="Banner Image">
    </div>
</div>
